<?php
return [
    // Prodotti per "Ristorante La Piazza"
    [
        'name' => 'Pizza Margherita',
        'description' => 'La tradizionale pizza margherita con pomodoro, mozzarella e basilico.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Diavola',
        'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Quattro Stagioni',
        'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi, carciofi e olive.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Capricciosa',
        'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi e carciofi.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Marinara',
        'description' => 'Pizza con pomodoro, aglio, origano e olio d\'oliva.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Napoli',
        'description' => 'Pizza con pomodoro, mozzarella, acciughe e capperi.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Quattro Formaggi',
        'description' => 'Pizza con una miscela di quattro formaggi.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Vegetariana',
        'description' => 'Pizza con pomodoro, mozzarella e verdure miste.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Prosciutto e Funghi',
        'description' => 'Pizza con pomodoro, mozzarella, prosciutto cotto e funghi.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    [
        'name' => 'Pizza Boscaiola',
        'description' => 'Pizza con pomodoro, mozzarella, funghi e salsiccia.',
        'product_type_id' => 2,
        'restaurant_id' => 1,
    ],
    // Prodotti per "Trattoria da Luigi"
    [
        'name' => 'Spaghetti alla Carbonara',
        'description' => 'Spaghetti conditi con una cremosa salsa a base di uova, pancetta e pecorino romano.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Lasagne al Forno',
        'description' => 'Pasta a strati con ragù, besciamella e formaggio.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Risotto alla Milanese',
        'description' => 'Risotto preparato con zafferano e brodo di carne.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Penne all\'Arrabbiata',
        'description' => 'Pasta con salsa di pomodoro piccante e peperoncino.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Tagliatelle al Ragù',
        'description' => 'Pasta con ragù di carne.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Gnocchi al Pesto',
        'description' => 'Gnocchi con salsa al pesto.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Ravioli di Ricotta e Spinaci',
        'description' => 'Ravioli ripieni di ricotta e spinaci.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Tortellini in Brodo',
        'description' => 'Tortellini serviti in brodo caldo.',
        'product_type_id' => 3,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Pizza Margherita',
        'description' => 'La tradizionale pizza margherita con pomodoro, mozzarella e basilico.',
        'product_type_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Pizza Quattro Stagioni',
        'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi, carciofi e olive.',
        'product_type_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Pizza Diavola',
        'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
        'product_type_id' => 2,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Tiramisu',
        'description' => 'Un dolce al cucchiaio a base di caffè, mascarpone e cacao.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Panna Cotta',
        'description' => 'Dolce al cucchiaio a base di panna, servito con salsa ai frutti di bosco.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Gelato Artigianale',
        'description' => 'Gelato preparato artigianalmente con ingredienti freschi.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Torta della Nonna',
        'description' => 'Torta ripiena di crema pasticcera e pinoli.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Profiteroles',
        'description' => 'Dolce composto da bignè ripieni di crema e ricoperti di cioccolato.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Cannoli Siciliani',
        'description' => 'Dolce siciliano con ricotta e scorze di arancia candite.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Zuppa Inglese',
        'description' => 'Dolce al cucchiaio con strati di crema pasticcera e savoiardi imbevuti di alchermes.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    [
        'name' => 'Tartufo',
        'description' => 'Dolce al cioccolato ripieno di gelato e ricoperto di cacao in polvere.',
        'product_type_id' => 7,
        'restaurant_id' => 2,
    ],
    // Prodotti per "Sakura Sushi"
    [
        'name' => 'Sushi Nigiri',
        'description' => 'Riso con fettine di pesce crudo sopra.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Sashimi',
        'description' => 'Fettine di pesce crudo servite con salsa di soia.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'California Roll',
        'description' => 'Roll di sushi con avocado, cetriolo e surimi.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Tempura di Gamberi',
        'description' => 'Gamberi fritti in pastella croccante.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Ramen',
        'description' => 'Zuppa di noodles con brodo di carne e verdure.',
        'product_type_id' => 11,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Tonkatsu',
        'description' => 'Cotoletta di maiale fritta servita con salsa tonkatsu.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Miso Soup',
        'description' => 'Zuppa di miso con tofu e alghe.',
        'product_type_id' => 11,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Gyoza',
        'description' => 'Ravioli di carne e verdure cotti al vapore e poi alla piastra.',
        'product_type_id' => 10,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Udon',
        'description' => 'Spaghetti di grano spessi serviti in brodo di pesce o carne.',
        'product_type_id' => 11,
        'restaurant_id' => 3,
    ],
    [
        'name' => 'Matcha Ice Cream',
        'description' => 'Gelato al tè verde matcha.',
        'product_type_id' => 7,
        'restaurant_id' => 3,
    ],
    // Prodotti per "El Ranchito"
    [
        'name' => 'Tacos al Pastor',
        'description' => 'Tacos con carne di maiale marinata e ananas.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Burrito di Pollo',
        'description' => 'Tortilla ripiena di pollo, riso, fagioli e verdure.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Quesadilla',
        'description' => 'Tortilla ripiena di formaggio fuso e verdure.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Guacamole',
        'description' => 'Crema di avocado con cipolla, pomodoro e lime.',
        'product_type_id' => 12,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Enchiladas',
        'description' => 'Tortillas ripiene di carne, ricoperte di salsa e formaggio.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Fajitas di Manzo',
        'description' => 'Strisce di manzo saltate con peperoni e cipolle.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Nachos con Formaggio',
        'description' => 'Tortilla chips ricoperte di formaggio fuso.',
        'product_type_id' => 4,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Churros',
        'description' => 'Dolci fritti serviti con zucchero e cannella.',
        'product_type_id' => 7,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Torta Tres Leches',
        'description' => 'Torta bagnata con tre tipi di latte.',
        'product_type_id' => 7,
        'restaurant_id' => 4,
    ],
    [
        'name' => 'Margarita',
        'description' => 'Cocktail a base di tequila, lime e triple sec.',
        'product_type_id' => 5,
        'restaurant_id' => 4,
    ],
    // Prodotti per "Taj Mahal Indian Restaurant"
    [
        'name' => 'Chicken Tikka Masala',
        'description' => 'Pollo marinato in spezie e yogurt, cotto in salsa di pomodoro e spezie.',
        'product_type_id' => 4,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Naan',
        'description' => 'Pane indiano cotto nel forno tandoor.',
        'product_type_id' => 1,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Biryani',
        'description' => 'Riso basmati con carne e spezie.',
        'product_type_id' => 3,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Samosa',
        'description' => 'Triangoli di pasta ripieni di verdure speziate.',
        'product_type_id' => 4,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Tandoori Chicken',
        'description' => 'Pollo marinato con spezie e cotto nel forno tandoor.',
        'product_type_id' => 4,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Lassi',
        'description' => 'Bevanda a base di yogurt, dolce o salata.',
        'product_type_id' => 5,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Raita',
        'description' => 'Yogurt con cetriolo e spezie.',
        'product_type_id' => 12,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Gulab Jamun',
        'description' => 'Dolcetti fritti immersi in sciroppo di zucchero.',
        'product_type_id' => 7,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Palak Paneer',
        'description' => 'Formaggio fresco in salsa di spinaci e spezie.',
        'product_type_id' => 4,
        'restaurant_id' => 5,
    ],
    [
        'name' => 'Mango Chutney',
        'description' => 'Chutney di mango con spezie dolci e piccanti.',
        'product_type_id' => 12,
        'restaurant_id' => 5,
    ],
    // Prodotti per "Olympus Taverna"
    [
        'name' => 'Moussaka',
        'description' => 'Sformato di melanzane, carne e besciamella.',
        'product_type_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Gyros',
        'description' => 'Carne di maiale cotta su uno spiedo verticale, servita con pita e salsa tzatziki.',
        'product_type_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Souvlaki',
        'description' => 'Spiedini di carne grigliati.',
        'product_type_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Dolmades',
        'description' => 'Foglie di vite ripiene di riso e carne.',
        'product_type_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Tzatziki',
        'description' => 'Salsa di yogurt, cetriolo e aglio.',
        'product_type_id' => 12,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Spanakopita',
        'description' => 'Torta salata di spinaci e feta.',
        'product_type_id' => 4,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Horiatiki',
        'description' => 'Insalata greca con pomodori, cetrioli, olive e feta.',
        'product_type_id' => 9,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Baklava',
        'description' => 'Dolce a base di pasta fillo, noci e miele.',
        'product_type_id' => 7,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Retsina',
        'description' => 'Vino bianco aromatizzato con resina di pino.',
        'product_type_id' => 5,
        'restaurant_id' => 6,
    ],
    [
        'name' => 'Loukoumades',
        'description' => 'Frittelle dolci immerse nel miele.',
        'product_type_id' => 7,
        'restaurant_id' => 6,
    ],
    // Prodotti per "Bangkok Street Food"
    [
        'name' => 'Pad Thai',
        'description' => 'Noodles saltati con gamberi, tofu, uova e arachidi.',
        'product_type_id' => 3,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Tom Yum Soup',
        'description' => 'Zuppa piccante con gamberi, funghi e lime.',
        'product_type_id' => 11,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Green Curry',
        'description' => 'Curry verde con pollo e verdure.',
        'product_type_id' => 4,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Som Tum',
        'description' => 'Insalata di papaya verde con arachidi e pomodori.',
        'product_type_id' => 9,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Spring Rolls',
        'description' => 'Involtini primavera fritti ripieni di verdure.',
        'product_type_id' => 4,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Mango Sticky Rice',
        'description' => 'Riso appiccicoso con mango fresco e latte di cocco.',
        'product_type_id' => 7,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Satay di Pollo',
        'description' => 'Spiedini di pollo serviti con salsa di arachidi.',
        'product_type_id' => 4,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Red Curry',
        'description' => 'Curry rosso con manzo e verdure.',
        'product_type_id' => 4,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Thai Iced Tea',
        'description' => 'Tè freddo dolce con latte condensato.',
        'product_type_id' => 5,
        'restaurant_id' => 7,
    ],
    [
        'name' => 'Chicken Larb',
        'description' => 'Insalata di pollo tritato con erbe fresche e lime.',
        'product_type_id' => 9,
        'restaurant_id' => 7,
    ],
    // Prodotti per "Le Bistro Français"
    [
        'name' => 'Croissant',
        'description' => 'Pasta sfoglia a forma di mezzaluna.',
        'product_type_id' => 1,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Escargots de Bourgogne',
        'description' => 'Lumache cotte con burro alle erbe.',
        'product_type_id' => 4,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Coq au Vin',
        'description' => 'Pollo brasato nel vino rosso con funghi e pancetta.',
        'product_type_id' => 4,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Quiche Lorraine',
        'description' => 'Torta salata con pancetta e formaggio.',
        'product_type_id' => 4,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Soupe à l\'Oignon',
        'description' => 'Zuppa di cipolle gratinata.',
        'product_type_id' => 11,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Ratatouille',
        'description' => 'Stufato di verdure provenzale.',
        'product_type_id' => 4,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Crème Brûlée',
        'description' => 'Dolce a base di crema con crosta di zucchero caramellato.',
        'product_type_id' => 7,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Boeuf Bourguignon',
        'description' => 'Stufato di manzo cotto nel vino rosso.',
        'product_type_id' => 4,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Tarte Tatin',
        'description' => 'Torta di mele rovesciata caramellata.',
        'product_type_id' => 7,
        'restaurant_id' => 8,
    ],
    [
        'name' => 'Mousse au Chocolat',
        'description' => 'Dolce al cioccolato spumoso.',
        'product_type_id' => 7,
        'restaurant_id' => 8,
    ],
    // Prodotti per "Cantina Mexicana"
    [
        'name' => 'Taco di Manzo',
        'description' => 'Taco con carne di manzo, lattuga, formaggio e salsa.',
        'product_type_id' => 4,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Burrito Vegetariano',
        'description' => 'Tortilla ripiena di riso, fagioli, verdure e formaggio.',
        'product_type_id' => 4,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Queso Fundido',
        'description' => 'Formaggio fuso con peperoni e salsiccia.',
        'product_type_id' => 4,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Ceviche',
        'description' => 'Pesce marinato nel lime con pomodori, cipolla e coriandolo.',
        'product_type_id' => 4,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Pozole',
        'description' => 'Zuppa di maiale con mais bianco e spezie.',
        'product_type_id' => 11,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Flan',
        'description' => 'Dessert al caramello a base di uova e latte.',
        'product_type_id' => 7,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Tamales',
        'description' => 'Impasto di mais ripieno di carne, cotto in foglie di mais.',
        'product_type_id' => 4,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Sopa de Tortilla',
        'description' => 'Zuppa di pomodoro con strisce di tortilla fritte.',
        'product_type_id' => 11,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Arroz con Leche',
        'description' => 'Riso dolce con latte e cannella.',
        'product_type_id' => 7,
        'restaurant_id' => 9,
    ],
    [
        'name' => 'Michelada',
        'description' => 'Cocktail di birra con lime, salsa piccante e spezie.',
        'product_type_id' => 5,
        'restaurant_id' => 9,
    ],
    // Prodotti per "Pizzeria Napoli"
    [
        'name' => 'Pizza Funghi',
        'description' => 'Pizza con pomodoro, mozzarella e funghi freschi.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Quattro Formaggi',
        'description' => 'Pizza con una miscela di quattro formaggi.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Diavola',
        'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Capricciosa',
        'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi e carciofi.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Ortolana',
        'description' => 'Pizza con pomodoro, mozzarella e verdure grigliate.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Boscaiola',
        'description' => 'Pizza con pomodoro, mozzarella, funghi e salsiccia.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Tonno e Cipolla',
        'description' => 'Pizza con pomodoro, mozzarella, tonno e cipolla.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Salsiccia e Friarielli',
        'description' => 'Pizza con salsiccia e friarielli.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Parmigiana',
        'description' => 'Pizza con pomodoro, mozzarella e melanzane.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    [
        'name' => 'Pizza Pugliese',
        'description' => 'Pizza con pomodoro, mozzarella e cipolla rossa.',
        'product_type_id' => 2,
        'restaurant_id' => 10,
    ],
    // Prodotti per "Gelateria Dolce Vita"
    [
        'name' => 'Gelato al Cioccolato',
        'description' => 'Gelato artigianale al cioccolato fondente.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato alla Vaniglia',
        'description' => 'Gelato artigianale alla vaniglia.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato al Pistacchio',
        'description' => 'Gelato artigianale al pistacchio.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Sorbetto al Limone',
        'description' => 'Sorbetto rinfrescante al limone.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato alla Fragola',
        'description' => 'Gelato artigianale alla fragola.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato al Caffè',
        'description' => 'Gelato artigianale al caffè.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato alla Nocciola',
        'description' => 'Gelato artigianale alla nocciola.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato al Limone',
        'description' => 'Gelato artigianale al limone.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Coppa Amarena',
        'description' => 'Gelato con amarene sciroppate.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
    [
        'name' => 'Gelato al Mango',
        'description' => 'Gelato artigianale al mango.',
        'product_type_id' => 7,
        'restaurant_id' => 11,
    ],
];
