<?php
return [
  // Prodotti per "Ristorante La Piazza"
  [
    'name' => 'Pizza Margherita',
    'description' => 'La tradizionale pizza margherita con pomodoro, mozzarella e basilico.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-margherita.png',
  ],
  [
    'name' => 'Pizza Diavola',
    'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-diavola.png',
  ],
  [
    'name' => 'Pizza Quattro Stagioni',
    'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi, carciofi e olive.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-quattro-stagioni.png',
  ],
  [
    'name' => 'Pizza Capricciosa',
    'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi e carciofi.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-capricciosa.png',
  ],
  [
    'name' => 'Pizza Marinara',
    'description' => 'Pizza con pomodoro, aglio, origano e olio d\'oliva.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-marinara.png',
  ],
  [
    'name' => 'Pizza Napoli',
    'description' => 'Pizza con pomodoro, mozzarella, acciughe e capperi.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-napoli.png',
  ],
  [
    'name' => 'Pizza Quattro Formaggi',
    'description' => 'Pizza con una miscela di quattro formaggi.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-quattro-formaggi.png',
  ],
  [
    'name' => 'Pizza Vegetariana',
    'description' => 'Pizza con pomodoro, mozzarella e verdure miste.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-vegetariana.png',
  ],
  [
    'name' => 'Pizza Prosciutto e Funghi',
    'description' => 'Pizza con pomodoro, mozzarella, prosciutto cotto e funghi.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-prosciutto-e-funghi.png',
  ],
  [
    'name' => 'Pizza Boscaiola',
    'description' => 'Pizza con pomodoro, mozzarella, funghi e salsiccia.',
    'product_type_id' => 2,
    'restaurant_id' => 1,
    'image' => 'uploads/pizza-boscaiola.png',
  ],
  // Prodotti per "Trattoria da Luigi"
  [
    'name' => 'Spaghetti alla Carbonara',
    'description' => 'Spaghetti conditi con una cremosa salsa a base di uova, pancetta e pecorino romano.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Lasagne al Forno',
    'description' => 'Pasta a strati con ragù, besciamella e formaggio.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Risotto alla Milanese',
    'description' => 'Risotto preparato con zafferano e brodo di carne.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Penne all\'Arrabbiata',
    'description' => 'Pasta con salsa di pomodoro piccante e peperoncino.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Tagliatelle al Ragù',
    'description' => 'Pasta con ragù di carne.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Gnocchi al Pesto',
    'description' => 'Gnocchi con salsa al pesto.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Ravioli di Ricotta e Spinaci',
    'description' => 'Ravioli ripieni di ricotta e spinaci.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Tortellini in Brodo',
    'description' => 'Tortellini serviti in brodo caldo.',
    'product_type_id' => 3,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Pizza Margherita',
    'description' => 'La tradizionale pizza margherita con pomodoro, mozzarella e basilico.',
    'product_type_id' => 2,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Pizza Quattro Stagioni',
    'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi, carciofi e olive.',
    'product_type_id' => 2,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Pizza Diavola',
    'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
    'product_type_id' => 2,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Tiramisu',
    'description' => 'Un dolce al cucchiaio a base di caffè, mascarpone e cacao.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Panna Cotta',
    'description' => 'Dolce al cucchiaio a base di panna, servito con salsa ai frutti di bosco.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Gelato Artigianale',
    'description' => 'Gelato preparato artigianalmente con ingredienti freschi.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Torta della Nonna',
    'description' => 'Torta ripiena di crema pasticcera e pinoli.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Profiteroles',
    'description' => 'Dolce composto da bignè ripieni di crema e ricoperti di cioccolato.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Cannoli Siciliani',
    'description' => 'Dolce siciliano con ricotta e scorze di arancia candite.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Zuppa Inglese',
    'description' => 'Dolce al cucchiaio con strati di crema pasticcera e savoiardi imbevuti di alchermes.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  [
    'name' => 'Tartufo',
    'description' => 'Dolce al cioccolato ripieno di gelato e ricoperto di cacao in polvere.',
    'product_type_id' => 7,
    'restaurant_id' => 2,
    'image' => null,
  ],
  // Prodotti per "Sakura Sushi"
  [
    'name' => 'Sushi Nigiri',
    'description' => 'Riso con fettine di pesce crudo sopra.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Sashimi',
    'description' => 'Fettine di pesce crudo servite con salsa di soia.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'California Roll',
    'description' => 'Roll di sushi con avocado, cetriolo e surimi.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Tempura di Gamberi',
    'description' => 'Gamberi fritti in pastella croccante.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Ramen',
    'description' => 'Zuppa di noodles con brodo di carne e verdure.',
    'product_type_id' => 11,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Tonkatsu',
    'description' => 'Cotoletta di maiale fritta servita con salsa tonkatsu.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Miso Soup',
    'description' => 'Zuppa di miso con tofu e alghe.',
    'product_type_id' => 11,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Gyoza',
    'description' => 'Ravioli di carne e verdure cotti al vapore e poi alla piastra.',
    'product_type_id' => 10,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Udon',
    'description' => 'Spaghetti di grano spessi serviti in brodo di pesce o carne.',
    'product_type_id' => 11,
    'restaurant_id' => 3,
    'image' => null,
  ],
  [
    'name' => 'Matcha Ice Cream',
    'description' => 'Gelato al tè verde matcha.',
    'product_type_id' => 7,
    'restaurant_id' => 3,
    'image' => null,
  ],
  // Prodotti per "El Ranchito"
  [
    'name' => 'Tacos al Pastor',
    'description' => 'Tacos con carne di maiale marinata e ananas.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Burrito di Pollo',
    'description' => 'Tortilla ripiena di pollo, riso, fagioli e verdure.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Quesadilla',
    'description' => 'Tortilla ripiena di formaggio fuso e verdure.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Guacamole',
    'description' => 'Crema di avocado con cipolla, pomodoro e lime.',
    'product_type_id' => 12,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Enchiladas',
    'description' => 'Tortillas ripiene di carne, ricoperte di salsa e formaggio.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Fajitas di Manzo',
    'description' => 'Strisce di manzo saltate con peperoni e cipolle.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Nachos con Formaggio',
    'description' => 'Tortilla chips ricoperte di formaggio fuso.',
    'product_type_id' => 4,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Churros',
    'description' => 'Dolci fritti serviti con zucchero e cannella.',
    'product_type_id' => 7,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Torta Tres Leches',
    'description' => 'Torta bagnata con tre tipi di latte.',
    'product_type_id' => 7,
    'restaurant_id' => 4,
    'image' => null,
  ],
  [
    'name' => 'Margarita',
    'description' => 'Cocktail a base di tequila, lime e triple sec.',
    'product_type_id' => 5,
    'restaurant_id' => 4,
    'image' => null,
  ],
  // Prodotti per "Taj Mahal Indian Restaurant"
  [
    'name' => 'Chicken Tikka Masala',
    'description' => 'Pollo marinato in spezie e yogurt, cotto in salsa di pomodoro e spezie.',
    'product_type_id' => 4,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Naan',
    'description' => 'Pane indiano cotto nel forno tandoor.',
    'product_type_id' => 1,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Biryani',
    'description' => 'Riso basmati con carne e spezie.',
    'product_type_id' => 3,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Samosa',
    'description' => 'Triangoli di pasta ripieni di verdure speziate.',
    'product_type_id' => 4,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Tandoori Chicken',
    'description' => 'Pollo marinato con spezie e cotto nel forno tandoor.',
    'product_type_id' => 4,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Lassi',
    'description' => 'Bevanda a base di yogurt, dolce o salata.',
    'product_type_id' => 5,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Raita',
    'description' => 'Yogurt con cetriolo e spezie.',
    'product_type_id' => 12,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Gulab Jamun',
    'description' => 'Dolcetti fritti immersi in sciroppo di zucchero.',
    'product_type_id' => 7,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Palak Paneer',
    'description' => 'Formaggio fresco in salsa di spinaci e spezie.',
    'product_type_id' => 4,
    'restaurant_id' => 5,
    'image' => null,
  ],
  [
    'name' => 'Mango Chutney',
    'description' => 'Chutney di mango con spezie dolci e piccanti.',
    'product_type_id' => 12,
    'restaurant_id' => 5,
    'image' => null,
  ],
  // Prodotti per "Olympus Taverna"
  [
    'name' => 'Moussaka',
    'description' => 'Sformato di melanzane, carne e besciamella.',
    'product_type_id' => 4,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Gyros',
    'description' => 'Carne di maiale cotta su uno spiedo verticale, servita con pita e salsa tzatziki.',
    'product_type_id' => 4,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Souvlaki',
    'description' => 'Spiedini di carne grigliati.',
    'product_type_id' => 4,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Dolmades',
    'description' => 'Foglie di vite ripiene di riso e carne.',
    'product_type_id' => 4,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Tzatziki',
    'description' => 'Salsa di yogurt, cetriolo e aglio.',
    'product_type_id' => 12,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Spanakopita',
    'description' => 'Torta salata di spinaci e feta.',
    'product_type_id' => 4,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Horiatiki',
    'description' => 'Insalata greca con pomodori, cetrioli, olive e feta.',
    'product_type_id' => 9,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Baklava',
    'description' => 'Dolce a base di pasta fillo, noci e miele.',
    'product_type_id' => 7,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Retsina',
    'description' => 'Vino bianco aromatizzato con resina di pino.',
    'product_type_id' => 5,
    'restaurant_id' => 6,
    'image' => null,
  ],
  [
    'name' => 'Loukoumades',
    'description' => 'Frittelle dolci immerse nel miele.',
    'product_type_id' => 7,
    'restaurant_id' => 6,
    'image' => null,
  ],
  // Prodotti per "Bangkok Street Food"
  [
    'name' => 'Pad Thai',
    'description' => 'Noodles saltati con gamberi, tofu, uova e arachidi.',
    'product_type_id' => 3,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Tom Yum Soup',
    'description' => 'Zuppa piccante con gamberi, funghi e lime.',
    'product_type_id' => 11,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Green Curry',
    'description' => 'Curry verde con pollo e verdure.',
    'product_type_id' => 4,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Som Tum',
    'description' => 'Insalata di papaya verde con arachidi e pomodori.',
    'product_type_id' => 9,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Spring Rolls',
    'description' => 'Involtini primavera fritti ripieni di verdure.',
    'product_type_id' => 4,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Mango Sticky Rice',
    'description' => 'Riso appiccicoso con mango fresco e latte di cocco.',
    'product_type_id' => 7,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Satay di Pollo',
    'description' => 'Spiedini di pollo serviti con salsa di arachidi.',
    'product_type_id' => 4,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Red Curry',
    'description' => 'Curry rosso con manzo e verdure.',
    'product_type_id' => 4,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Thai Iced Tea',
    'description' => 'Tè freddo dolce con latte condensato.',
    'product_type_id' => 5,
    'restaurant_id' => 7,
    'image' => null,
  ],
  [
    'name' => 'Chicken Larb',
    'description' => 'Insalata di pollo tritato con erbe fresche e lime.',
    'product_type_id' => 9,
    'restaurant_id' => 7,
    'image' => null,
  ],
  // Prodotti per "Le Bistro Français"
  [
    'name' => 'Croissant',
    'description' => 'Pasta sfoglia a forma di mezzaluna.',
    'product_type_id' => 1,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Escargots de Bourgogne',
    'description' => 'Lumache cotte con burro alle erbe.',
    'product_type_id' => 4,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Coq au Vin',
    'description' => 'Pollo brasato nel vino rosso con funghi e pancetta.',
    'product_type_id' => 4,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Quiche Lorraine',
    'description' => 'Torta salata con pancetta e formaggio.',
    'product_type_id' => 4,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Soupe à l\'Oignon',
    'description' => 'Zuppa di cipolle gratinata.',
    'product_type_id' => 11,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Ratatouille',
    'description' => 'Stufato di verdure provenzale.',
    'product_type_id' => 4,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Crème Brûlée',
    'description' => 'Dolce a base di crema con crosta di zucchero caramellato.',
    'product_type_id' => 7,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Boeuf Bourguignon',
    'description' => 'Stufato di manzo cotto nel vino rosso.',
    'product_type_id' => 4,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Tarte Tatin',
    'description' => 'Torta di mele rovesciata caramellata.',
    'product_type_id' => 7,
    'restaurant_id' => 8,
    'image' => null,
  ],
  [
    'name' => 'Mousse au Chocolat',
    'description' => 'Dolce al cioccolato spumoso.',
    'product_type_id' => 7,
    'restaurant_id' => 8,
    'image' => null,
  ],
  // Prodotti per "Cantina Mexicana"
  [
    'name' => 'Taco di Manzo',
    'description' => 'Taco con carne di manzo, lattuga, formaggio e salsa.',
    'product_type_id' => 4,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Burrito Vegetariano',
    'description' => 'Tortilla ripiena di riso, fagioli, verdure e formaggio.',
    'product_type_id' => 4,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Queso Fundido',
    'description' => 'Formaggio fuso con peperoni e salsiccia.',
    'product_type_id' => 4,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Ceviche',
    'description' => 'Pesce marinato nel lime con pomodori, cipolla e coriandolo.',
    'product_type_id' => 4,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Pozole',
    'description' => 'Zuppa di maiale con mais bianco e spezie.',
    'product_type_id' => 11,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Flan',
    'description' => 'Dessert al caramello a base di uova e latte.',
    'product_type_id' => 7,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Tamales',
    'description' => 'Impasto di mais ripieno di carne, cotto in foglie di mais.',
    'product_type_id' => 4,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Sopa de Tortilla',
    'description' => 'Zuppa di pomodoro con strisce di tortilla fritte.',
    'product_type_id' => 11,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Arroz con Leche',
    'description' => 'Riso dolce con latte e cannella.',
    'product_type_id' => 7,
    'restaurant_id' => 9,
    'image' => null,
  ],
  [
    'name' => 'Michelada',
    'description' => 'Cocktail di birra con lime, salsa piccante e spezie.',
    'product_type_id' => 5,
    'restaurant_id' => 9,
    'image' => null,
  ],
  // Prodotti per "Pizzeria Napoli"
  [
    'name' => 'Pizza Funghi',
    'description' => 'Pizza con pomodoro, mozzarella e funghi freschi.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Quattro Formaggi',
    'description' => 'Pizza con una miscela di quattro formaggi.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Diavola',
    'description' => 'Pizza con pomodoro, mozzarella e salame piccante.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Capricciosa',
    'description' => 'Pizza con pomodoro, mozzarella, prosciutto, funghi e carciofi.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Ortolana',
    'description' => 'Pizza con pomodoro, mozzarella e verdure grigliate.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Boscaiola',
    'description' => 'Pizza con pomodoro, mozzarella, funghi e salsiccia.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Tonno e Cipolla',
    'description' => 'Pizza con pomodoro, mozzarella, tonno e cipolla.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Salsiccia e Friarielli',
    'description' => 'Pizza con salsiccia e friarielli.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Parmigiana',
    'description' => 'Pizza con pomodoro, mozzarella e melanzane.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  [
    'name' => 'Pizza Pugliese',
    'description' => 'Pizza con pomodoro, mozzarella e cipolla rossa.',
    'product_type_id' => 2,
    'restaurant_id' => 10,
    'image' => null,
  ],
  // Prodotti per "Gelateria Dolce Vita"
  [
    'name' => 'Gelato al Cioccolato',
    'description' => 'Gelato artigianale al cioccolato fondente.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato alla Vaniglia',
    'description' => 'Gelato artigianale alla vaniglia.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato al Pistacchio',
    'description' => 'Gelato artigianale al pistacchio.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Sorbetto al Limone',
    'description' => 'Sorbetto rinfrescante al limone.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato alla Fragola',
    'description' => 'Gelato artigianale alla fragola.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato al Caffè',
    'description' => 'Gelato artigianale al caffè.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato alla Nocciola',
    'description' => 'Gelato artigianale alla nocciola.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato al Limone',
    'description' => 'Gelato artigianale al limone.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Coppa Amarena',
    'description' => 'Gelato con amarene sciroppate.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],
  [
    'name' => 'Gelato al Mango',
    'description' => 'Gelato artigianale al mango.',
    'product_type_id' => 7,
    'restaurant_id' => 11,
    'image' => null,
  ],

  // Smokehouse BBQ

  [
    'name' => 'Panino con Brisket',
    'description' => 'Brisket affumicato lentamente con salsa BBQ su un panino tostato.',
    'product_type_id' => 1,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Piatto di Costine',
    'description' => 'Costine di maiale cotte lentamente glassate nella nostra salsa BBQ.',
    'product_type_id' => 4,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Panino con Pulled Pork',
    'description' => 'Tenero pulled pork servito su un panino brioche con insalata di cavolo.',
    'product_type_id' => 1,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Ali di pollo BBQ',
    'description' => 'Ali di pollo croccanti cotte con salsa BBQ, servite con salsa ranch.',
    'product_type_id' => 4,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Piatto di Salsiccia Affumicata',
    'description' => 'Salsiccia affumicata succulenta servita con fagioli BBQ e pane di mais.',
    'product_type_id' => 4,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Brisket in Stile Texas',
    'description' => 'Brisket affumicato in stile tradizionale del Texas.',
    'product_type_id' => 4,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Pollo BBQ Sfilacciato',
    'description' => 'Pollo sfilacciato cotto lentamente con salsa BBQ, servito su un panino.',
    'product_type_id' => 4,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Pane di Mais con Burro al Miele',
    'description' => 'Pane di mais fatto in casa servito caldo con burro al miele montato.',
    'product_type_id' => 1,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Fagioli BBQ',
    'description' => 'Fagioli dal sapore BBQ cotti lentamente con un tocco affumicato.',
    'product_type_id' => 9,
    'restaurant_id' => 12,
    'image' => null,
  ],
  [
    'name' => 'Coleslaw Stile Sud',
    'description' => 'Coleslaw classico stile sud con una salsa dal gusto tangy.',
    'product_type_id' => 12,
    'restaurant_id' => 12,
    'image' => null,
  ],

  // Mamma Mia Pizzeria


  [
    'name' => 'Pizza Margherita',
    'description' => 'Pomodoro, mozzarella di bufala, basilico fresco.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Napoletana',
    'description' => 'Pomodoro, mozzarella fior di latte, acciughe, capperi, origano.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Quattro Stagioni',
    'description' => 'Pomodoro, mozzarella, funghi, prosciutto cotto, carciofi, olive nere.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Capricciosa',
    'description' => 'Pomodoro, mozzarella, prosciutto cotto, funghi, carciofi, olive.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Diavola',
    'description' => 'Pomodoro, mozzarella, salame piccante, peperoncini.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Quattro Formaggi',
    'description' => 'Mozzarella, gorgonzola, provola affumicata, parmigiano reggiano.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Calzone Classico',
    'description' => 'Impasto ripieno di pomodoro, mozzarella, prosciutto cotto, funghi.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Marinara',
    'description' => 'Pomodoro, aglio, origano, olio extravergine di oliva.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Frutti di Mare',
    'description' => 'Pomodoro, mozzarella, frutti di mare misti, aglio, prezzemolo.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],
  [
    'name' => 'Pizza Vegetariana',
    'description' => 'Pomodoro, mozzarella, peperoni, melanzane, zucchine, olive nere.',
    'product_type_id' => 2,
    'restaurant_id' => 13,
    'image' => null,
  ],

  // Turkish Delight

  [
    'name' => 'Kebab di Agnello',
    'description' => 'Agnello marinato e arrosto verticalmente, servito con riso pilaf e insalata.',
    'product_type_id' => 4,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Köfte',
    'description' => 'Polpette di carne macinata condite con spezie turche, accompagnate da bulgur e yogurt.',
    'product_type_id' => 4,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Hummus con Pita',
    'description' => 'Crema di ceci condita con olio d\'oliva, servita con pane pita caldo.',
    'product_type_id' => 8,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Dolma',
    'description' => 'Foglie di vite ripiene di riso condito con menta e spezie, servite con yogurt.',
    'product_type_id' => 9,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Pide alla Turchia',
    'description' => 'Focaccia turca ripiena con carne, formaggio e verdure, servita con insalata fresca.',
    'product_type_id' => 8,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Manti',
    'description' => 'Ravioli turchi ripieni di carne e conditi con salsa di pomodoro e yogurt.',
    'product_type_id' => 3,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Baklava',
    'description' => 'Dolce turco a base di pasta fillo, noci e miele.',
    'product_type_id' => 7,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Sarma',
    'description' => 'Foglie di vite ripiene di riso e carne, condite con limone e menta.',
    'product_type_id' => 9,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Çöp Şiş',
    'description' => 'Spiedini di carne marinata alla griglia, serviti con verdure alla brace.',
    'product_type_id' => 4,
    'restaurant_id' => 14,
    'image' => null,
  ],
  [
    'name' => 'Ayran',
    'description' => 'Bevanda tradizionale turca a base di yogurt, acqua e sale.',
    'product_type_id' => 5,
    'restaurant_id' => 14,
    'image' => null,
  ],

  // Prodotti per Lebanese Bistro

  [
    'name' => 'Hummus',
    'description' => 'Crema di ceci con tahina e limone.',
    'product_type_id' => 8,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Falafel',
    'description' => 'Polpette di ceci fritte.',
    'product_type_id' => 4,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Tabbouleh',
    'description' => 'Insalata di prezzemolo, pomodori e bulgur.',
    'product_type_id' => 9,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Shawarma',
    'description' => 'Carne arrostita servita con pane pita e salse.',
    'product_type_id' => 4,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Baba Ganoush',
    'description' => 'Crema di melanzane affumicate.',
    'product_type_id' => 9,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Kibbeh',
    'description' => 'Polpette di carne e bulgur fritte.',
    'product_type_id' => 4,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Manakish',
    'description' => 'Pizza libanese con za\'atar e olio d\'oliva.',
    'product_type_id' => 2,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Fattoush',
    'description' => 'Insalata con pane pita tostato e verdure fresche.',
    'product_type_id' => 9,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Baklava',
    'description' => 'Dolce di pasta fillo con miele e noci.',
    'product_type_id' => 7,
    'restaurant_id' => 15,
    'image' => null,
  ],
  [
    'name' => 'Arayes',
    'description' => 'Pane pita ripieno di carne macinata e spezie.',
    'product_type_id' => 9,
    'restaurant_id' => 15,
    'image' => null,
  ],

  // Prodotti per Fast & Fresh

  [
    'name' => 'Cheeseburger',
    'description' => 'Hamburger classico con formaggio, lattuga e pomodoro.',
    'product_type_id' => 1,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Chicken Nuggets',
    'description' => 'Bocconcini di pollo fritti.',
    'product_type_id' => 4,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'French Fries',
    'description' => 'Patatine fritte croccanti.',
    'product_type_id' => 9,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Hot Dog',
    'description' => 'Panino con wurstel, senape e ketchup.',
    'product_type_id' => 1,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Chicken Sandwich',
    'description' => 'Panino con pollo fritto, lattuga e maionese.',
    'product_type_id' => 1,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Veggie Burger',
    'description' => 'Hamburger vegetariano con formaggio, lattuga e pomodoro.',
    'product_type_id' => 4,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Milkshake',
    'description' => 'Frullato di gelato disponibile in vari gusti.',
    'product_type_id' => 5,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Onion Rings',
    'description' => 'Anelli di cipolla fritti.',
    'product_type_id' => 9,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'Grilled Chicken Salad',
    'description' => 'Insalata con pollo grigliato, lattuga, pomodori e formaggio.',
    'product_type_id' => 9,
    'restaurant_id' => 16,
    'image' => null,
  ],
  [
    'name' => 'BBQ Bacon Burger',
    'description' => 'Hamburger con pancetta, formaggio e salsa BBQ.',
    'product_type_id' => 1,
    'restaurant_id' => 16,
    'image' => null,
  ],

  // Prodotti per il Seafood Sensation

  [
    'name' => 'Fried Calamari',
    'description' => 'Anelli di calamari fritti serviti con salsa tartara.',
    'product_type_id' => 8,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Grilled Salmon',
    'description' => 'Salmone alla griglia servito con contorni di stagione.',
    'product_type_id' => 10,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Fish Tacos',
    'description' => 'Tacos con pesce fritto, cavolo e salsa cremosa.',
    'product_type_id' => 10,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Lobster Roll',
    'description' => 'Panino con aragosta e maionese.',
    'product_type_id' => 1,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Clam Chowder',
    'description' => 'Zuppa cremosa di vongole.',
    'product_type_id' => 11,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Shrimp Cocktail',
    'description' => 'Gamberetti serviti con salsa cocktail.',
    'product_type_id' => 8,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Fish and Chips',
    'description' => 'Pesce fritto servito con patatine fritte.',
    'product_type_id' => 10,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Seafood Paella',
    'description' => 'Paella con frutti di mare misti.',
    'product_type_id' => 10,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Crab Cakes',
    'description' => 'Tortini di granchio serviti con salsa remoulade.',
    'product_type_id' => 8,
    'restaurant_id' => 17,
    'image' => null,
  ],
  [
    'name' => 'Seafood Platter',
    'description' => 'Piatto misto di frutti di mare fritti.',
    'product_type_id' => 10,
    'restaurant_id' => 17,
    'image' => null,
  ],


  // Prodotti per "Steakhouse Deluxe"

  [
    'name' => 'Arista alla Fiorentina',
    'description' => 'Arrosto di maiale condito con aglio, rosmarino e pepe nero.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Tagliata di Manzo',
    'description' => 'Fettine di manzo grigliate, servite con rucola e scaglie di Parmigiano.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Costolette di Agnello alla Griglia',
    'description' => 'Costolette di agnello marinate e grigliate, condite con erbe aromatiche.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Pollo alla Diavola',
    'description' => 'Pollo marinato con spezie piccanti e grigliato alla brace.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Filetto di Cinghiale al Tartufo',
    'description' => 'Filetto di cinghiale servito con salsa al tartufo.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Ossobuco alla Milanese',
    'description' => 'Ossobuco di vitello cotto lentamente con vino bianco e gremolada.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Salsiccia alla Griglia',
    'description' => 'Salsiccia italiana grigliata, servita con contorno di verdure grigliate.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Brasato al Barolo',
    'description' => 'Manzo brasato lentamente con vino Barolo e aromi, servito con polenta.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Gnocchi di Patate al Gorgonzola e Noci',
    'description' => 'Gnocchi di patate con salsa cremosa di gorgonzola e noci.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],
  [
    'name' => 'Coda alla Vaccinara',
    'description' => 'Stufato di coda di bue con verdure, pomodoro e vino rosso.',
    'product_type_id' => 4,
    'restaurant_id' => 18,
    'image' => null,
  ],

  // Prodotti per "Burger Joint"

  [
    'name' => 'Burger Americano',
    'description' => 'Burger con carne di manzo grigliata, formaggio cheddar, lattuga, pomodoro e salsa BBQ.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Bacon & Cheese',
    'description' => 'Burger con carne di manzo, bacon croccante, formaggio svizzero, lattuga, cipolla e maionese.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Vegano',
    'description' => 'Burger vegetale a base di quinoa, ceci e verdure miste, servito con hummus e insalata fresca.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Barbecue Chicken',
    'description' => 'Burger con petto di pollo alla griglia, formaggio cheddar, cipolla rossa, lattuga e salsa barbecue.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Bacon & Egg',
    'description' => 'Burger con carne di manzo, bacon croccante, uovo al tegamino, formaggio cheddar, lattuga e maionese.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Hawaiano',
    'description' => 'Burger con carne di manzo, prosciutto cotto, ananas grigliato, formaggio svizzero, lattuga e salsa di mango.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Blue Cheese',
    'description' => 'Burger con carne di manzo, formaggio blue cheese, cipolla caramellata, lattuga e salsa aioli.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Ranchero',
    'description' => 'Burger con carne di manzo, bacon croccante, formaggio cheddar, jalapeÃ±os, lattuga e salsa ranch.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger Italiano',
    'description' => 'Burger con carne di manzo, mozzarella di bufala, pomodoro fresco, basilico e pesto alla genovese.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],
  [
    'name' => 'Burger BBQ Pulled Pork',
    'description' => 'Burger con carne di maiale stufato al barbecue, formaggio cheddar, crauti e salsa barbecue.',
    'product_type_id' => 4,
    'restaurant_id' => 19,
    'image' => null,
  ],

  // Prodotti per "Mediterranean Sunset"

  [
    'name' => 'Insalata Greca',
    'description' => 'Insalata fresca con pomodori, cetrioli, olive, cipolla rossa, feta e origano.',
    'product_type_id' => 9,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Moussaka',
    'description' => 'Piatto tradizionale greco con strati di melanzane, carne macinata e besciamella.',
    'product_type_id' => 9,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Souvlaki di Pollo',
    'description' => 'Spiedini di pollo marinato e grigliato, serviti con pita e salsa tzatziki.',
    'product_type_id' => 4,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Calamari Fritti',
    'description' => 'Calamari freschi fritti croccanti, serviti con salsa tzatziki.',
    'product_type_id' => 10,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Risotto ai Frutti di Mare',
    'description' => 'Risotto cremoso con frutti di mare freschi, prezzemolo e scaglie di parmigiano.',
    'product_type_id' => 10,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Polipo alla Griglia',
    'description' => 'Polipo grigliato servito con patate al forno e salsa di limone.',
    'product_type_id' => 10,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Baklava',
    'description' => 'Dolce tradizionale greco con strati di pasta fillo, noci e miele.',
    'product_type_id' => 7,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Tzatziki',
    'description' => 'Salsa di yogurt greco con cetrioli, aglio e erbe aromatiche.',
    'product_type_id' => 12,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Dolmades',
    'description' => 'Foglie di vite ripiene di riso aromatizzato, pinoli e uvetta.',
    'product_type_id' => 13,
    'restaurant_id' => 20,
    'image' => null,
  ],
  [
    'name' => 'Spanakopita',
    'description' => 'Pasticcio greco con spinaci, feta e erbe avvolte in pasta fillo croccante.',
    'product_type_id' => 9,
    'restaurant_id' => 20,
    'image' => null,
  ],


];
